### ISSUE TITLE
SleekDB is not compatible with ReactPHP

### ISSUE THREAD

**Issue by CaptainKant** [rakibtg/SleekDB#183] opened 2021-04-10 15:54 UTC
I use ReactPHP for async stuff.
I needed a simple no-sql database so I tried SleekDB : it seems that "findOneBy" query are stuck forever when used in a  parallel thread.

**Comment by Timu57** [comment] 2021-04-11 11:33
Hi @CaptainKant,
I don't know ReactPHP, do you know why this could happen?
Does other methods of SleekDB work?
Would be nice if you could provide more information.
Could that be a bug of ReactPHP?
Could you share the code that produce the error?

Thank you in advance.

**Comment by Timu57** [comment] 2021-04-13 16:09
With the information provided it is not possible to find out if the issue is caused by SleekDB, ReactPHP or because of wrong usage.

Due to the lack of information I will close this issue for now, feel free to reopen it if needed.

**Closed by Timu57** 2021-04-13 16:09 UTC
