### ISSUE TITLE
insert one json file

### ISSUE THREAD

**Issue by bahramzade** [rakibtg/SleekDB#231] opened 2022-04-03 21:34 UTC
Hello, when it runs, it creates a new file every time
how to make that would add data to one json file?
_id1 ?

$userStore = new Store('users', __DIR__ . "/database");
$user = [
    'name' => 'Kazi Hasan',
    'products' => [
        'totalSaved' => 19,
        'totalBought' => 27
    ],
    'location' => [
        'town' => 'Nagar',
        'city' => 'Dhaka',
        'country' => 'Bangladesh'
    ]
];
// Insert the data.
$user = $userStore->insert($user);

**Comment by bahramzade** [comment] 2022-04-03 22:03
one json, another data insert.
old data saving new  line

**Comment by xavierfoucrier** [comment] 2022-04-05 11:48
Expected behavior, duplicate of #176.
> You can close the issue :+1:

**Comment by Timu57** [comment] 2022-05-08 08:33
Like @xavierfoucrier said.

That is how SleekDB currently works.

We plan on implementing a "One File" solution in the future.
Unfortunately that is easier said than done in PHP.
We currently have an idea how we could make it work, but need to resolve some problems to implement it in an efficient and good way.

I am closing this issue for now. Feel free to reopen it if needed.

**Closed by Timu57** 2022-05-08 08:33 UTC
Labels: question
